[package]
name = "anixe"
version = "0.1.0"
authors = ["Bartłomiej Kuras <bartlomiej.kuras@o2.pl>"]

[dependencies]
argparse = "0.2.0"
serde = "1"
serde_derive = "1"
csv = "1"
chrono = { version = "0.4", features = ["serde"] }
